### ISSUE TITLE
es5 prototype function

### ISSUE THREAD

**Issue by francescoagati** [nanojsx/nano#119]
with es5 prototype function i get this errror

Class constructor cannot be invoked without 'new'"

**Comment by yandeu** [comment]
Why don't you use ES2015+?

**Comment by francescoagati** [comment]
I use or insider an es5 projectcfor now butciwoild likecto use nano

**Comment by yandeu** [comment]
I don't think you can use nano with es5. Just write it in ES2015+ (with or without JSX) and transpile it down using TypeScript or Babel.
