### ISSUE TITLE
Enhancement Suggestion: Making README Dark Mode Compatible

### ISSUE THREAD

**Issue by garronej** [nanojsx/nano#135]
Hello @yandeu,

I've noticed that the current README doesn't appear to be fully optimized for dark mode:

<img width="933" alt="image" src="https://github.com/nanojsx/nano/assets/6702424/82f49116-c218-4c55-9144-4d8a4d3c628c">

There are a couple of ways this can be addressed. One method could be by adding a white border to the "nano" text. Alternatively, consider creating a unique variant specifically for dark mode. As an illustration, see [i18nifty](https://github.com/etalab/i18nifty): [Light Mode](https://user-images.githubusercontent.com/6702424/200299948-94bacf9d-381e-40f8-b9a3-8e726bcd37c5.png) and [Dark Mode](https://user-images.githubusercontent.com/6702424/200299807-42388349-a5ae-44b2-abd1-0aa538b58da2.png). You can delve into the implementation details [here](https://github.com/etalab/i18nifty/blob/f6ad7bb11514224a416158af7af8e4073c7932c1/README.md?plain=1#L1-L11).

TS-CI offers [an additional action](https://github.com/garronej/ts-ci/blob/09916b317c55a04dbf2fc036d7343cd6c6756cc6/.github/workflows/ci.yaml#L105-L107) that can be useful: it removes the dark mode-specific image from your README.md before [publishing on NPM](https://www.npmjs.com/package/i18nifty), considering that NPM doesn't currently support the `#gh-dark-mode-only` syntax.

If you find these suggestions helpful, let me know if you'd like a Pull Request for these changes.

Best Regards,

**Comment by yandeu** [comment]
Thanks! I have thought about it for a long time, but did not find it enough important. I guess it's the best to create a new image for dark mode. If you want and have time feel free to upload a new logo with white text. I did not know that npm does not support the `#gh-dark-mode-only` syntax. What about deno.land/x?

**Comment by yandeu** [comment]
@garronej Btw, I didn't know you are using nano-jsx. (Do you?)

If yes, do you have a little feedback for me?

**Comment by yandeu** [comment]
> #gh-dark-mode-only

Looks like this method is deprecated. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

**Comment by garronej** [comment]
EDIT: Somethime it dosen't render with the correct asset for some reason though... 

<img width="918" alt="image" src="https://github.com/nanojsx/nano/assets/6702424/664729fc-ff31-44f9-9502-252bb090fc8c">

![image](https://github.com/nanojsx/nano/assets/6702424/e234acdb-66de-46c6-aed7-9c14cf4703bc)

I guess it's a bug with GitHub that'll get resolver sooner or later.

**Comment by yandeu** [comment]
Maybe it depends on the browser? It falls back to the original (black color) if no color schema is detected?

**Comment by garronej** [comment]
No... it's random.  

https://github.com/nanojsx/nano/assets/6702424/168ff9ce-4563-4acd-8809-907bf426ed4b

**Comment by yandeu** [comment]
Strange. On my phone it works every time. Light colors everytime, and in Battery Save Mode dark colors.
_Android + Chrome incognito mode_

**Comment by garronej** [comment]
I wouldn't worry about it. I think GitHub will fix the issue.
