### ISSUE TITLE
[BUG] navigating away from a non-existent route doesn't trigger update

### ISSUE THREAD

**Issue by raminjafary** [nanojsx/nano#18]
When navigating away from a non-existent route, `this.path` and `this.index` is the same as `this.match.path` and `this.match.index`. In this case, the component will never call update. As a workaround, we can reset `this.path` and `this.index` when there is no route to match.

**Comment by yandeu** [comment]
Hey @raminjafary thanks a lot for all your contributions!

Should I release another version after the PR is merged?

_I will have a look at it tomorrow_

**Comment by raminjafary** [comment]
My pleasure! Thanks.
I think that'd be great if you do so.
