### ISSUE TITLE
renderSSR error when using a component defined with a regular JS function

### ISSUE THREAD

**Issue by dsego** [nanojsx/nano#4]
This is the Oak route that tries to render a NanoJSX component.
```js
import { App } from "./views/App.jsx"
router.get("/", (ctx) => {
  ctx.response.body = `<html><body>${Nano.renderSSR(Nano.h(App), null)}</body></html>`
});
```
A component defined as an arrow function works fine, without issues:
```js
export const App = () => {
  return <h1> Hello App </h1>
}
```

A component defined as a regular (named or anon) JS function doesn't work.
```js
export function App () {
  return <h1> Hello App </h1>
}
```
This is the error:
```
Component.willMount is not a function

TypeError: Component.willMount is not a function
    at renderComponent (core.ts:124:15)
    at render (core.ts:69:12)
    at Module.renderSSR (ssr.ts:12:10)
```

tsconfig
```
{
  "compilerOptions": {
    "lib": ["esnext", "dom", "dom.iterable", "deno.ns", "deno.unstable"]
    "strictPropertyInitialization": false,
    "jsx": "react",
    "jsxFactory": "Nano.h"
  }
}
```

**Comment by yandeu** [comment]
I see. I made a very dumb mistake. 🤣

I will provide a fix as soon as I'm back at my desk.
(< 2 hours)

**Comment by yandeu** [comment]
The problem is [this line](https://github.com/nanojsx/nano/blob/master/src/helpers.ts#L3).
If `renderSSR()` gets called a second time, `hasWindow` will be true, which results in `isSSR` to be false.

I have added a `Hello.tsx` component to the [nano-jsx-deno-dev](https://github.com/nanojsx/nano-jsx-deno-dev) with a quick hack. Have a look!


```tsx
// Hello.tsx

// I import only h, since I have defined "jsxFactory": "h", in tsconfig.json.
import { h } from 'https://deno.land/x/nano_jsx@v0.0.11/mod.ts'

export const Hello = () => {
  return <h1>Hello Nano App!</h1>
}
```
```tsx
// server.tsx

// set isSSR manuall to true
// @ts-ignore
globalThis.isSSR = true
// @ts-ignore
globalThis.document = new DocumentSSR()

// do this
render(<Hello />, null, true).join('')
// instead of this
renderSSR(<Hello />)

```
---

Btw, if you wonder why the Helmet component is not working: It has already been fixed [here](https://github.com/nanojsx/nano/commit/6773a946a7a2f42bd1d6ec7d27b2b43b6ae4882d).

**Comment by dsego** [comment]
Thanks @yandeu for your help. I will close the ticket. :raised_hands: :pray:

**Comment by yandeu** [comment]
You're welcome.
I will just let it open until I have implemented the fix.

**Comment by yandeu** [comment]
I have just published version 12. And the issue is gone :)

**Comment by yandeu** [comment]
Check out the latest deno example at https://github.com/nanojsx/nano-jsx-deno-example
