### ISSUE TITLE
security: nanojsx does not escape text and attributes when doing SSR

### ISSUE THREAD

**Issue by lucacasonato** [nanojsx/nano#40]
**Describe the bug**

React and Preact both escape text fragments and element attributes when doing SSR. nanojsx does not. I would argue nanojsx should do this too.

You can see what I mean at https://dash.deno.com/playground/nanojsx-escape.

**Comment by yandeu** [comment]
Btw @lucacasonato, your example (https://dash.deno.com/playground/nanojsx-escape) works now as expected.  
(_just need to fork/update the deno playground_)
