### ISSUE TITLE
Add documentation for router listener

### ISSUE THREAD

**Issue by yandeu** [nanojsx/nano#53]
Add documentation for router listener.

See:
- https://github.com/nanojsx/nano/blob/router-dev-1/src/dev/dev.tsx
- https://github.com/nanojsx/nano/blob/router-listener-example/src/dev/dev.tsx

**Comment by jrson83** [comment]
It would be awesome if the documentation is ready soon. I tried setting it up but I don't know how to work with the uncompiled source code and couldn't get it running.

**Comment by yandeu** [comment]
I wrote a real world example for you [here](https://github.com/nanojsx/nano/blob/router-listener-example/src/dev/dev.tsx).

The docs will follow soon.

## Basically; 

- `<Switch />` will only trigger a re-render if the `<Route />` component changes.
- If `<Route />` has a dynamic path like `<Route exact path="/blog/:id">` and the user navigates from `/blog/584` to `/blog/219`, `<Switch />` will NOT trigger a re-render and the user will never see `/blog/219`. 
- _Solution:_ You can use the Router Listener inside `<Blog />` to listen for route changes. This will allow you to fetch the new blog post (based on the new id in "/blog/:id") and update the component.

**Comment by yandeu** [comment]
_Btw, thanks a lot for your [huge donation](https://github.com/sponsors/yandeu)_ :heart_eyes:

**Comment by jrson83** [comment]
No problem man. Awesome this is exactly what I'm looking for since days. I'll test it later today.

**Comment by yandeu** [comment]
There is now a video available about the Router Listener:
https://youtu.be/eUBuFORqPdo
