### ISSUE TITLE
Images are not displayed with Img component

### ISSUE THREAD

**Issue by jrson83** [nanojsx/nano#58]
**Describe the bug**
I tried using the v23 Img component with `.svg`, `.png` and `.jpg`, but the images are not shown.
```javascript
import { Img } from 'nano-jsx/lib/components/img'
...
<Img class="footer-logo" src="/public/img/footer-logo.png" alt="Logo" />
...
```
Checked the HTML in inspector. It's kind of getting crippled:
```html
<div style=";" class="footer-logo" alt=""></div>
```

**Comment by yandeu** [comment]
It is a placeholder. This component is isomorphic. Use the same code on the client and the server.

**Comment by jrson83** [comment]
> It is a placeholder. This component is isomorphic. Use the same code on the client and the server.

Ah ok, thank you! Slowly I begin to understand. When I render or hydrate the component, the image gets displayed.
