### ISSUE TITLE
Router.Switch fallback does'nt do anything

### ISSUE THREAD

**Issue by luaVolk** [nanojsx/nano#7]
In [this example](https://nanojsx.github.io/components.html#router) it shows that you can give a fallback to the `Switch` component but it doesn't do anything. It always just renders `not found`

**Comment by yandeu** [comment]
Do you use it client-side or server-side?

Yes, when no path matches, it renders `() => <div>404 (not found)</div>`.

**Comment by luaVolk** [comment]
I'm using it in both and it renders `not found` in both. Not `<div>404 (not found)</div>`.

Looking at https://github.com/nanojsx/nano/blob/master/src/components/router.ts#L96 there doesn't seem to be any mention of a fallback prop.

**Comment by yandeu** [comment]
You're right. I forgot to merge the latest router branch. I have just merged it now (https://github.com/nanojsx/nano/commit/874efffebd4feb02b4e85eb7c06df39efe6a3d00).

`path="*"` does also catch all paths. Place the code below at the very bottom of the `Switch`.

```tsx
<Router.Route path="*">{() => <div>404 (not found)</div>}</Router.Route>
```

**Comment by luaVolk** [comment]
Ah ok, thank you. I'll do that for now

**Comment by yandeu** [comment]
You're welcome :smiley: 

Don't hesitate to ask if you encounter any other problems!

**Comment by yandeu** [comment]
I just improved the 2 `<Router />` test files. I'm sure they will also help:
- [client-side](https://github.com/nanojsx/nano/blob/master/test/router.test.tsx)
- [server-side](https://github.com/nanojsx/nano/blob/master/test/router.ssr.test.tsx)
