### ISSUE TITLE
[Analysis] customElementsMode.js Types and behaviour of attributeChangedCallback()

### ISSUE THREAD

**Issue by jrson83** [nanojsx/nano#74]
### customElementsMode.js prop key types = always string
I tested a lot whith CustomElements.js. First I created a simple counter component, but without passing a value (props). It was working as expected, but i had to call `this.update()` inside the `changeValue()` function, to update the component.

Then I passed the props key `value` to the component. It was not working as expected, since the type of value was always `string`. I tried different approaches to change the value type to number or convert to Int/Number, but nothing worked.

### Behaviour of `attributeChangedCallback()`
After I read all the docs about Custom Webcomponents, I was wondering, why actually I had to call `this.update()` at all, since `attributeChangedCallback` actually should update the component itself. I analysed the code of CustomElements.
In my understanding, the function `attributeChangedCallback` in customElementsMode.js will NEVER get executed in your code, because it NEEDS to call `setAttribute` to execute. [Please read here](https://alligator.io/web-components/attributes-properties/).

**Have a question?**
I don't know maybe I was just trying too many hours to archive the desired results.
But I have setup a repo with 3 different demonstrations.

[https://github.com/jrson83/nanojsx-elements-test](https://github.com/jrson83/nanojsx-elements-test)
- **counter_simple.tsx** : for demonstrating `prop key type is always string`
- **counter.tsx** : more advanced approach with more debuging
- **word.tsx** : for demonstrating that attributeChangedCallback actually only works with setAttribute

There are also comments inside the files, for more information. To change the compiled file just change the entry in webpack.config.js.
It would be great if you checkout the repo and give some feedback on my thougts.

**Comment by yandeu** [comment]
- counter_simple.tsx  
  In the web, the value of an html attributes can only be of type string.
- counter.tsx  
  If you manually create a `WebComponent`, you can use `attributeChangedCallback` to update things. In nanojsx you have to call update(). `attributeChangedCallback` will only be called once internally.
- word.tsx  
  If you want to update the value on the DOM you can do this. But I don't see the use of it.

**Comment by jrson83** [comment]
Thanks, I suspected this and should not have spent so much time analyzing the functions. I close the issue.
