### ISSUE TITLE
Improve dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by yandeu** [nanojsx/nano#76]
Use
```tsx
<div innerHTML={{ __dangerousHtml: html }} />
```
instead of
```tsx
<div dangerouslySetInnerHTML={{ __html: html }} />
```

Why?

- easier to read
- looking just at `{ __dangerousHtml: html }` lets the user suspect a danger 

## TODOs

- [x] #78
- [x] Implement modern __dangerousHtml syntax.

**Comment by Shinyaigeek** [comment]
Hi @yandeu :wave:

I think many of `nano-jsx`’s user expect `nano-jsx` to provide a similar API to React/Preact and keeping similar to the React/Preact API will lead to allow us to reuse React’s type definitions, and more user-friendly API and developer experience. How about do you think?

**Comment by yandeu** [comment]
I will keep both. But update to docs to the new syntax.
Please see: https://www.youtube.com/watch?v=XEt09iK8IXs&t=495s

**Comment by Shinyaigeek** [comment]
I see. I did not know about this video. 

I totally agree providing new dangelouslySetInnerHTML syntax and keeping both of API! Thank you for sharing the video!
