### ISSUE TITLE
[Request]  Please add a changelog.md

### ISSUE THREAD

**Issue by jrson83** [nanojsx/nano#79]
**Describe the Request**
It would be totally awesome if you could add a `changelog.md` to the repo. I have no experience with, but here are some helpful websites:

https://keepachangelog.com/en/1.1.0/
https://www.mokkapps.de/blog/how-to-automatically-generate-a-helpful-changelog-from-your-git-commit-messages/

**Have a question?**
What you think?

**Comment by yandeu** [comment]
I do not use a changelog in any of my projects. Besides adding new feature (which will be documented on the homepage), I rarely remove features. When I remove features, I show a deprecated message first for a long time.

Maybe a changelog makes sens once the project reaches v1.0.0.
