### ISSUE TITLE
[Bug] didUnmount() event console.log() fired too late on page change

### ISSUE THREAD

**Issue by jrson83** [nanojsx/nano#87]
**Describe the bug**
Install the [router listener example](https://github.com/nanojsx/nano/blob/router-listener-example/src/dev/dev.tsx) and add a `didUnmount()` with `console.log()` to every component, like there is already for the `didMount()`:

```js
didUnmount() {
  console.log('[HomePage] didUnmount')
}
```

Run the app, click on About then Blog 219. You will see the console output in this order:

```
07:52:14.738 [HomePage] constructor
07:52:14.741 [HomePage] didMount
-> Click About

07:52:17.285 [AboutPage] constructor
07:52:17.285 [AboutPage] didMount
07:52:17.285 [HomePage] didUnmount
-> Click Blog 219

07:52:19.238 [BlogPage] constructor
07:52:19.238 [BlogPage] didMount
07:52:19.239 [AboutPage] didUnmount
```

**Have a question?**
This might not be a big issue but this is very confusing. I spent hours testing with jest why components on my adapter unmount for no reason. Finally when I reproduced with router listener example, I recognized this is default behaviour.
It would be great if we can fix this issue, since it might confuse people when debugging. If this is and should be default behaviour this should be written as notice in the docs.

**Comment by yandeu** [comment]
This is the normal behavior. `didMount()` will only be called once the node has been detached from the DOM.
Yes, maybe we should add a notice to the documentation.
