### ISSUE TITLE
[Bug] New Helmet client-side TypeError with external template file

### ISSUE THREAD

**Issue by jrson83** [nanojsx/nano#95]
**Describe the bug**

When using Helmet on the client side only, with an external template file, it is throwing an error as soon as you add more then one tag to the `<Helmet />`. This was not an issue before the new [helmet update](https://github.com/nanojsx/nano/commit/2a4b73843655b9b23b0a8c7e24859030d1a02d3a).

```js
<Helmet>
  <title>{this.props.title ? this.props.title : '404 Error'} - Nano JSX</title>
  {/* Helmet crashing, when using an external template file, and adding more then one tag to the helmet */}
  <meta name="description" content="Nano-JSX application" />
</Helmet>
```

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')`

Pointing to this [line of code](https://github.com/nanojsx/nano/blob/master/src/components/helmet.ts#L88):
```js
for (let r = 0; r < e.attributes.length; r++)
```

Just to demonstrate [I created a repo](https://github.com/jrson83/nano-jsx-helmet-bug).

**Comment by yandeu** [comment]
The issue is the jsx-runtime.

Use:
```json
"jsx": "react",
"jsxFactory": "h",
"jsxFragmentFactory": "Fragment",
```
And don't use `children` as a props like here: `<Layout children={page} title="About" />`
Do `<Layout title="About">{page}</Layout>` instead.

**Comment by jrson83** [comment]
Why is the runtime the issue? When I use those options my VS Code is freaking out and every line of code is red:
```TS2304: Cannot find name 'h'.```

**Comment by yandeu** [comment]
Use `import { h } from `nano-jsx/lib/core` on every page for now.
