### ISSUE TITLE
New JSX Transform API won't work on deno

### ISSUE THREAD

**Issue by aiotter** [nanojsx/nano#96]
**Describe the bug**
Putting `/** @jsxImportSource https://deno.land/x/nano_jsx@v0.0.26 */` at the first line of a `.tsx` file won't work because no such file (404) as `https://deno.land/x/nano_jsx@v0.0.26/jsx-runtime`.
The same for esm.sh(500 for `error: parseCJSModuleExports: Can't resolve 'nano-jsx/jsx-runtime'`), cdn.skypack.dev(404), unpkg.com(404).

None of the CDNs above can resolve `nano-jsx/lib/jsx-runtime` either.

On v0.0.21, which is the first release after #29 got merged, esm.sh can resolve `nano-jsx@0.0.21`.
However it causes compile error `TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.` as already reported at #52 (and fixed at f2b72f4).

**Comment by yandeu** [comment]
I don't know. There are currently limitations with the jsx-runtime in deno. See https://deno.land/manual@v1.16.0/jsx_dom/jsx.

Please just use the non-jsx-runtime syntax as used in the [deno example](https://github.com/nanojsx/nano-jsx-deno-example) for now.

**Comment by aiotter** [comment]
I found a workaround for this.
You can use import map to resolve `nano_jsx@v0.0.26/jsx-runtime` on deno.land/x.

```json
{
  "imports": {
    "nano/jsx-runtime": "https://deno.land/x/nano_jsx@v0.0.26/jsx-runtime/index.ts"
  }
}
```

I don't know why esm.sh or other CDNs are unable to solve the problem, but the problem is on their side, not Nano's.
It might be a problem of esbuild? Whatsoever, sorry for reporting on wrong repo, and I'll share the workaround for those who has the same problem.

**Comment by yandeu** [comment]
> I don't know why esm.sh or other CDNs are unable to build the module, but it is sure that the problem is on their side, not Nano's.

Don't you think it's because NanoJSX outputs cjs instead of esm?

**Comment by aiotter** [comment]
In my understanding, both esm.sh and skypack.dev convert CJS into ESM. So there may be something wrong with that conversion. I know esm.sh uses esbuild for it, but not sure for skypack.dev.

I tested jspm.dev, another CDN with CJS to ESM conversion. They use RollupJS for it.
It emits `TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists`.
