### ISSUE TITLE
Body not expected

### ISSUE THREAD

**Issue by herudi** [nanojsx/nano#99]
hi, i try SSR with Deno but body not expected. thanks. 

Code :
```ts
/** @jsx h */

import { h, renderSSR, Helmet } from 'https://deno.land/x/nano_jsx@v0.0.29/mod.ts';

const App = () => {
    const handle = () => { console.log('hello'); };
    return <button onClick={handle} class="hello world">Click</button>;
}

const app = renderSSR(<App />);
const { body } = Helmet.SSR(app);

console.log(body);

// <button onClick="()= class="hello world">{ console.log('hello'); }">Click</button>
```

**Comment by yandeu** [comment]
What do you mean with "body not expected"?

**Comment by herudi** [comment]
body not expected : 
```html
<button onClick="()= class="hello world">{ console.log('hello'); }">Click</button>
```

body is expected :
```html
<button onClick="()=>{ console.log('hello'); }" class="hello world">Click</button>
```

**Comment by yandeu** [comment]
I see. The output should actually be `<button class="hello world">Click</button>` because SSR should remove all events. All event should be added during hydration.

**Comment by herudi** [comment]
yeah, all events should be removed if ssr. and added in client hydrate.

**Comment by yandeu** [comment]
Already fixed and published.

**Comment by herudi** [comment]
@yandeu thanks for fixed and published. BTW, i build simple SSR site with deno and nanojsx. https://maze-ssr.deno.dev/

**Comment by yandeu** [comment]
Looks great.

`Deno.emit` in dev and esbuild in prod?

**Comment by herudi** [comment]
Yes, `Deno.emit` so fast. but in prod need minify and code splitting. esbuild the right choice.

**Comment by jrson83** [comment]
> Yes, `Deno.emit` so fast. but in prod need minify and code splitting. esbuild the right choice.

Yes, way to go today is vite, rollup, esbuild or for bundle files microbundler. Webpack is so 1990.

**Comment by yandeu** [comment]
I don't know. Webpack for me is still the winner since it is sooo flexible. I use it in dev only. Production is always build on my CI/CD pipeline.

---

Also, vite uses rollup in dev, which is, well, much slower than webpack.

**Comment by herudi** [comment]
when i use nodejs, then webpack or rollup is the right choice for me. but unfortunately it doesn't support deno yet. except use `--compat`, I haven't tried it.
